
//! Autogenerated weights for `pallet_assets_bridge`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 42.0.1
//! DATE: 2025-02-05, STEPS: `100`, REPEAT: `100`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `station`, CPU: `AMD Ryzen Threadripper PRO 5945WX 12-Cores`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// target/release/timechain-node
// benchmark
// pallet
// --pallet=pallet_assets_bridge
// --extrinsic=*
// --dev
// --wasm-execution=compiled
// --repeat=100
// --steps=100
// --output=runtime/src/weights/develop/

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use polkadot_sdk::*;

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_assets_bridge`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_assets_bridge::WeightInfo for WeightInfo<T> {
	/// Storage: `AssetsBridge::Network` (r:1 w:1)
	/// Proof: `AssetsBridge::Network` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Tasks::OpsInsertIndex` (r:1 w:1)
	/// Proof: `Tasks::OpsInsertIndex` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Tasks::Ops` (r:0 w:1)
	/// Proof: `Tasks::Ops` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn teleport_keep_alive() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `275`
		//  Estimated: `3740`
		// Minimum execution time: 53_080_000 picoseconds.
		Weight::from_parts(54_393_000, 0)
			.saturating_add(Weight::from_parts(0, 3740))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `AssetsBridge::Network` (r:1 w:1)
	/// Proof: `AssetsBridge::Network` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Tasks::OpsInsertIndex` (r:1 w:1)
	/// Proof: `Tasks::OpsInsertIndex` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Tasks::Ops` (r:0 w:1)
	/// Proof: `Tasks::Ops` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn force_teleport() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `275`
		//  Estimated: `3740`
		// Minimum execution time: 53_451_000 picoseconds.
		Weight::from_parts(54_813_000, 0)
			.saturating_add(Weight::from_parts(0, 3740))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `AssetsBridge::Network` (r:1 w:1)
	/// Proof: `AssetsBridge::Network` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn register_network() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `76`
		//  Estimated: `3541`
		// Minimum execution time: 10_340_000 picoseconds.
		Weight::from_parts(10_700_000, 0)
			.saturating_add(Weight::from_parts(0, 3541))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `AssetsBridge::Network` (r:1 w:1)
	/// Proof: `AssetsBridge::Network` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn force_update_network() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `195`
		//  Estimated: `3660`
		// Minimum execution time: 10_580_000 picoseconds.
		Weight::from_parts(10_931_000, 0)
			.saturating_add(Weight::from_parts(0, 3660))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
