//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "feed")]
pub struct Model {
	#[sea_orm(primary_key)]
	pub id: i32,
	pub task_id: i64,
	pub hash: String,
	#[sea_orm(column_type = "Binary(BlobSize::Blob(None))")]
	pub task: Vec<u8>,
	pub validity: i32,
	pub timestamp: Option<TimeDateTime>,
	pub cycle: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
