[package]
name = "gmp-evm"
authors.workspace = true
edition.workspace = true
version.workspace = true
homepage.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true

[dependencies]
alloy = { git = "https://github.com/alloy-rs/alloy.git", branch = "yash/ws-reconnect", default-features = false, features = [
    "full",
    "rpc-types-debug",
    "rpc-types-trace",
    "json-rpc",
    "rpc-client",
    "signer-mnemonic",
] }
anyhow.workspace = true
async-trait.workspace = true
futures.workspace = true
hex.workspace = true
hex-literal.workspace = true
reqwest.workspace = true
sha3 = { version = "0.10", default-features = false }
serde.workspace = true
serde_json.workspace = true
thiserror = "2.0.12"
time-primitives = { workspace = true, default-features = true }
tokio = { workspace = true, features = ["time"] }
tracing.workspace = true
