[package]
name = "gmp-evm"
authors.workspace = true
edition.workspace = true
version.workspace = true
homepage.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true

[dependencies]
alloy = { version = "^0.12", features = [
    "full",
    "rpc-types-debug",
    "rpc-types-trace",
    "json-rpc",
    "rpc-client",
    "signer-ledger",
    "signer-mnemonic",
] }
anyhow.workspace = true
async-trait.workspace = true
futures.workspace = true
hex.workspace = true
reqwest.workspace = true
rosetta-client = { git = "https://github.com/analog-labs/chain-connectors", rev = "e066b7d130db482a93672a4c0153312832353a90" }
sha3 = { version = "0.10", default-features = false }
serde.workspace = true
serde_json.workspace = true
thiserror = "2.0.9"
time-primitives = { workspace = true, default-features = true }
tokio.workspace = true
tracing.workspace = true
hex-literal = "0.4.1"
