[package]
name = "gmp-evm"
version = "0.3.0"

authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true

[dependencies]
alloy.workspace = true
anyhow.workspace = true
async-trait.workspace = true
coins-ledger = { version = "0.12", default-features = false }
futures.workspace = true
futures-util = "0.3"
hex.workspace = true
hex-literal.workspace = true
reqwest.workspace = true
sha3 = { version = "0.10", default-features = false }
serde.workspace = true
serde_json.workspace = true
time-primitives = { workspace = true, default-features = true }
tokio = { workspace = true, features = ["time"] }
tracing.workspace = true
governor = "0.5.1"
num-traits = "0.2.19"
