[package]
name = "pallet-assets-bridge"
description = "A pallet that bridges assets"
publish = false

version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[package.metadata.docs.rs]
targets = [ "x86_64-unknown-linux-gnu" ]

[dependencies]
log.workspace = true
scale-codec.workspace = true
scale-info.workspace = true
simple-mermaid.workspace = true

polkadot-sdk = { workspace = true, features = [
	"frame-support",
	"frame-system",
	"sp-core",
	"sp-runtime",
	"sp-std",
]}


time-primitives.workspace = true

[dev-dependencies]
env_logger.workspace = true
lazy_static = "1.4.0"

pallet-networks.workspace = true
pallet-tasks.workspace = true
pallet-members.workspace = true
pallet-elections.workspace = true
pallet-shards.workspace = true

polkadot-sdk = { workspace = true, features = [
	 "sp-io",
	 "sp-keystore",

	 "pallet-treasury",
	 "pallet-balances",
]}

[features]
default = [ "std" ]
std = [
	"scale-codec/std",
	"scale-info/std",

	"polkadot-sdk/std",

	"pallet-elections/std",
	"pallet-members/std",
	"pallet-networks/std",
	"pallet-shards/std",
	"pallet-tasks/std",
	"time-primitives/std",
]
runtime-benchmarks = [
	"polkadot-sdk/runtime-benchmarks",
	"polkadot-sdk/frame-benchmarking",

	"pallet-elections/runtime-benchmarks",
	"pallet-networks/runtime-benchmarks",
	"pallet-members/runtime-benchmarks",
	"pallet-shards/runtime-benchmarks",
	"pallet-tasks/runtime-benchmarks",
]
try-runtime = [
	"polkadot-sdk/try-runtime",

	"pallet-elections/try-runtime",
	"pallet-networks/try-runtime",
	"pallet-members/try-runtime",
	"pallet-shards/try-runtime",
	"pallet-tasks/try-runtime",
]
