{
 "title": "Network Debugging",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "query": { "query": "label_values(pod)" } },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Unstable Peer-to-Peer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "instance" },
  {
   "title": "Closed Connection Reason",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(substrate_sub_libp2p_connections_closed_total{}[10m])",
     "legendFormat": "{{reason}} ({{direction}})"
    }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "substrate_sub_libp2p_peers_count{}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Handshake Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(substrate_sub_libp2p_incoming_connections_handshake_errors_total{}[10m])",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Network Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(substrate_sub_libp2p_out_events_events_total{}[10m])",
     "legendFormat": "{{name}} - {{event_name}}"
    }
   ]
  },
  {
   "title": "Pending Connection Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "rate(substrate_sub_libp2p_pending_connections_errors_total{}[10m])",
     "legendFormat": "{{reason}}"
    }
   ]
  }
 ]
}