FROM ghcr.io/foundry-rs/foundry:latest as foundry

FROM ubuntu:22.04
RUN apt-get update && apt-get install -y gnupg curl && \
    curl -fsSL https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x871920D1991BC93C | gpg --dearmor -o /usr/share/keyrings/ubuntu-archive-keyring.gpg && \
    echo "deb [signed-by=/usr/share/keyrings/ubuntu-archive-keyring.gpg] http://archive.ubuntu.com/ubuntu jammy main restricted universe multiverse" > /etc/apt/sources.list && \
    echo "deb [signed-by=/usr/share/keyrings/ubuntu-archive-keyring.gpg] http://archive.ubuntu.com/ubuntu jammy-updates main restricted universe multiverse" >> /etc/apt/sources.list && \
    echo "deb [signed-by=/usr/share/keyrings/ubuntu-archive-keyring.gpg] http://archive.ubuntu.com/ubuntu jammy-backports main restricted universe multiverse" >> /etc/apt/sources.list && \
    echo "deb [signed-by=/usr/share/keyrings/ubuntu-archive-keyring.gpg] http://security.ubuntu.com/ubuntu jammy-security main restricted universe multiverse" >> /etc/apt/sources.list && \
    apt-get update && apt-get install -y ca-certificates
COPY --from=foundry /usr/local/bin/cast /bin/cast
COPY tc-cli /bin/tc-cli
COPY envs /etc/envs
COPY analog-gmp /analog-gmp
ENV ANALOG_GMP_DIR /analog-gmp
ENTRYPOINT ["/bin/tc-cli"]
