FROM ubuntu:22.04
WORKDIR /app

COPY tester-bin tester
COPY out/ /etc/contracts

RUN apt update && apt install -y wget

RUN wget -O /app/foundry.tar.gz https://github.com/foundry-rs/foundry/releases/download/nightly/foundry_nightly_linux_amd64.tar.gz
RUN tar -xvzf /app/foundry.tar.gz -C /usr/local/bin

ENTRYPOINT ["/app/tester"]