FROM rust:1.76-buster
RUN apt update && apt install -y docker.io
RUN apt install -y software-properties-common gcc-8
RUN cargo install svm-rs
RUN svm install 0.8.24
RUN svm use 0.8.24
COPY tester tester
ENTRYPOINT ["/tester"]
