FROM ubuntu:22.04
RUN apt update && apt install -y docker.io
RUN apt install -y software-properties-common
RUN add-apt-repository ppa:ethereum/ethereum
RUN apt update && apt install -y solc
COPY tester tester
COPY out /etc/contracts/
ENTRYPOINT ["/tester"]