# dcode/constants.py

AVALON_CONSTANTS = {
    'GROUND_STATE_7': 7.0,
    'SANCTUARY_TIME': 144,
    'ATOMIC_GESTURE_MAX': 5,
    'QUANTUM_LEAP_THRESHOLD': 0.33,
    'EXCLUSION_THRESHOLD': 0.95,
    'FIELD_COHERENCE': 144.963,
    'SATOSHI_FREQUENCY': 31.4159,
    'DIAMOND_LATTICE_CONSTANT': 3.567,
    'NUCLEAR_BATTERY_HALFLIFE': 100,
    'CONSCIOUSNESS_DIFFUSION': 0.01,
    'KABBALAH_TEMPERATURE': 310.15
}

PSYCHIC_CONSTANTS = {
    'NEURAL_MANIFOLD_DIM': 3,
    'SPEED_OF_THOUGHT': 120,
    'SYNAPTIC_DELAY': 0.001,
    'NEURAL_ENTROPY': 0.693,
    'CONSCIOUSNESS_CAPACITY': 2.5e15,
    'REALITY_REFRESH_RATE': 144,
    'PSYCHIC_WAVELENGTH': 7.5e-7,
    'RESONANCE_QUALITY': 144
}

CRYPTO_CONSTANTS = {
    'SATOSHI_SATOSHI': 1e-8,
    'HASH_COMPLEXITY': 2**256,
    'GALOIS_FIELDS': 2**256 - 2**32 - 977,
    'ELLIPTIC_CURVES': 'y² = x³ + ax + b'
}
