config:
  chronicle_funds: 10.
  timechain_url: 'wss://archive.integration.analog.one'
  prices_path: 'prices.csv'
  testers_path: 'testers.csv'
backends:
  evm:
    chain_dict: "auxiliary/chains.json"
    proxy: "contracts/ERC1967Proxy.sol/ERC1967Proxy.json"
    gateway: "contracts/Gateway.sol/Gateway.json"
    tester: "contracts/GmpProxy.sol/GmpProxy.json"
networks:
  10:
    backend: "evm"
    name: "ethereum sepolia"
    url: "wss://ethereum-sepolia-rpc.publicnode.com"
    gateway_funds: 1.
    chronicle_funds: .1
    batch_size: 16
    batch_offset: 0
    batch_gas_limit: 18000000
    gmp_margin: 0.0
    shard_task_limit: 100
    route_gas_limit: 10000000
    route_base_fee: 1400000000
    shard_size: 1
    shard_threshold: 1
    coin_id: 1027
    session_gas: 50000
    session_exec_gas: 50000
    session_msg_byte_gas: 20
  13:
    backend: "evm"
    name: "arbitrum sepolia"
    url: "wss://arbitrum-sepolia-rpc.publicnode.com"
    gateway_funds: 1.
    chronicle_funds: .5
    batch_size: 1024
    batch_offset: 0
    batch_gas_limit: 500000000000000
    gmp_margin: 0.0
    shard_task_limit: 100
    route_gas_limit: 10000000
    route_base_fee: 1400000000
    shard_size: 1
    shard_threshold: 1
    coin_id: 1027
    session_gas: 50000
    session_exec_gas: 50000
    session_msg_byte_gas: 20
chronicles: 
- https://chronicle-1.integration.analog.one
- https://chronicle-19.integration.analog.one
