
//! Autogenerated weights for `bridge_multisig`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 42.0.1
//! DATE: 2025-02-11, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `ns1026992`, CPU: `AMD EPYC 4244P 6-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// ./target/testnet/timechain-node
// benchmark
// pallet
// --pallet
// bridge_multisig
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// ./runtime/src/weights/testnet/bridge_multisig.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use polkadot_sdk::*;

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `bridge_multisig`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> bridge_multisig::WeightInfo for WeightInfo<T> {
	/// Storage: `BridgeMultisig::Accounts` (r:1 w:0)
	/// Proof: `BridgeMultisig::Accounts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BridgeMultisig::Multisigs` (r:1 w:1)
	/// Proof: `BridgeMultisig::Multisigs` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BridgeMultisig::DispatchedCalls` (r:1 w:0)
	/// Proof: `BridgeMultisig::DispatchedCalls` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `s` is `[2, 100]`.
	/// The range of component `z` is `[0, 10000]`.
	fn as_multi_create(s: u32, z: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `111 + s * (32 ±0)`
		//  Estimated: `3576 + s * (32 ±0)`
		// Minimum execution time: 19_356_000 picoseconds.
		Weight::from_parts(16_987_868, 0)
			.saturating_add(Weight::from_parts(0, 3576))
			// Standard Error: 326
			.saturating_add(Weight::from_parts(27_835, 0).saturating_mul(s.into()))
			// Standard Error: 3
			.saturating_add(Weight::from_parts(840, 0).saturating_mul(z.into()))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
			.saturating_add(Weight::from_parts(0, 32).saturating_mul(s.into()))
	}
	/// Storage: `BridgeMultisig::Accounts` (r:1 w:0)
	/// Proof: `BridgeMultisig::Accounts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BridgeMultisig::Multisigs` (r:1 w:1)
	/// Proof: `BridgeMultisig::Multisigs` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BridgeMultisig::DispatchedCalls` (r:1 w:0)
	/// Proof: `BridgeMultisig::DispatchedCalls` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `s` is `[3, 100]`.
	/// The range of component `z` is `[0, 10000]`.
	fn as_multi_approve(s: u32, z: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `348 + s * (32 ±0)`
		//  Estimated: `3813 + s * (32 ±0)`
		// Minimum execution time: 20_348_000 picoseconds.
		Weight::from_parts(18_137_480, 0)
			.saturating_add(Weight::from_parts(0, 3813))
			// Standard Error: 285
			.saturating_add(Weight::from_parts(27_974, 0).saturating_mul(s.into()))
			// Standard Error: 2
			.saturating_add(Weight::from_parts(889, 0).saturating_mul(z.into()))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
			.saturating_add(Weight::from_parts(0, 32).saturating_mul(s.into()))
	}
	/// Storage: `BridgeMultisig::Accounts` (r:1 w:0)
	/// Proof: `BridgeMultisig::Accounts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BridgeMultisig::Multisigs` (r:1 w:1)
	/// Proof: `BridgeMultisig::Multisigs` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BridgeMultisig::DispatchedCalls` (r:1 w:1)
	/// Proof: `BridgeMultisig::DispatchedCalls` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `BridgeMultisig::Calls` (r:1 w:1)
	/// Proof: `BridgeMultisig::Calls` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `s` is `[2, 100]`.
	/// The range of component `z` is `[0, 10000]`.
	fn as_multi_complete(s: u32, z: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `381 + s * (53 ±0) + z * (1 ±0)`
		//  Estimated: `3841 + s * (53 ±0) + z * (1 ±0)`
		// Minimum execution time: 27_962_000 picoseconds.
		Weight::from_parts(24_695_454, 0)
			.saturating_add(Weight::from_parts(0, 3841))
			// Standard Error: 596
			.saturating_add(Weight::from_parts(41_003, 0).saturating_mul(s.into()))
			// Standard Error: 5
			.saturating_add(Weight::from_parts(1_343, 0).saturating_mul(z.into()))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(3))
			.saturating_add(Weight::from_parts(0, 53).saturating_mul(s.into()))
			.saturating_add(Weight::from_parts(0, 1).saturating_mul(z.into()))
	}
}
