
//! Autogenerated weights for `pallet_networks`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 47.2.0
//! DATE: 2025-06-06, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `benchmark-agent-1`, CPU: `AMD EPYC Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: 1024

// Executed Command:
// ./timechain-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_networks
// --extrinsic
// *
// --output
// ./testnet/pallet_networks.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use polkadot_sdk::*;

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_networks`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_networks::WeightInfo for WeightInfo<T> {
	/// Storage: `Networks::Networks` (r:1 w:1)
	/// Proof: `Networks::Networks` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Networks::NetworkGatewayAddress` (r:1 w:1)
	/// Proof: `Networks::NetworkGatewayAddress` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Networks::NetworkBatchSize` (r:1 w:1)
	/// Proof: `Networks::NetworkBatchSize` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Networks::NetworkBatchOffset` (r:1 w:1)
	/// Proof: `Networks::NetworkBatchOffset` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Tasks::TaskIdCounter` (r:1 w:1)
	/// Proof: `Tasks::TaskIdCounter` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Tasks::TaskCount` (r:1 w:1)
	/// Proof: `Tasks::TaskCount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Networks::NetworkShardSize` (r:0 w:1)
	/// Proof: `Networks::NetworkShardSize` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Networks::NetworkMsgOpExecGas` (r:0 w:1)
	/// Proof: `Networks::NetworkMsgOpExecGas` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Networks::NetworkRegOpExecGas` (r:0 w:1)
	/// Proof: `Networks::NetworkRegOpExecGas` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Networks::NetworkName` (r:0 w:1)
	/// Proof: `Networks::NetworkName` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Networks::NetworkShardThreshold` (r:0 w:1)
	/// Proof: `Networks::NetworkShardThreshold` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Networks::NetworkShardTaskLimit` (r:0 w:1)
	/// Proof: `Networks::NetworkShardTaskLimit` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Networks::NetworkUnregOpExecGas` (r:0 w:1)
	/// Proof: `Networks::NetworkUnregOpExecGas` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Networks::NetworkBatchExecGas` (r:0 w:1)
	/// Proof: `Networks::NetworkBatchExecGas` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Networks::NetworkGatewayBlock` (r:0 w:1)
	/// Proof: `Networks::NetworkGatewayBlock` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Networks::NetworkMsgByteGas` (r:0 w:1)
	/// Proof: `Networks::NetworkMsgByteGas` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Networks::NetworkBatchGasLimit` (r:0 w:1)
	/// Proof: `Networks::NetworkBatchGasLimit` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Tasks::SyncHeight` (r:0 w:1)
	/// Proof: `Tasks::SyncHeight` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Tasks::Tasks` (r:0 w:1)
	/// Proof: `Tasks::Tasks` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Tasks::ReadEventsTask` (r:0 w:1)
	/// Proof: `Tasks::ReadEventsTask` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Tasks::TaskNetwork` (r:0 w:1)
	/// Proof: `Tasks::TaskNetwork` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `a` is `[1, 50]`.
	fn register_network(a: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `184`
		//  Estimated: `3649`
		// Minimum execution time: 97_021_000 picoseconds.
		Weight::from_parts(105_892_640, 0)
			.saturating_add(Weight::from_parts(0, 3649))
			// Standard Error: 36_074
			.saturating_add(Weight::from_parts(133_905, 0).saturating_mul(a.into()))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(21))
	}
	/// Storage: `Networks::Networks` (r:1 w:0)
	/// Proof: `Networks::Networks` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Networks::NetworkShardSize` (r:0 w:1)
	/// Proof: `Networks::NetworkShardSize` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Networks::NetworkBatchOffset` (r:0 w:1)
	/// Proof: `Networks::NetworkBatchOffset` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Networks::NetworkMsgOpExecGas` (r:0 w:1)
	/// Proof: `Networks::NetworkMsgOpExecGas` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Networks::NetworkRegOpExecGas` (r:0 w:1)
	/// Proof: `Networks::NetworkRegOpExecGas` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Networks::NetworkBatchSize` (r:0 w:1)
	/// Proof: `Networks::NetworkBatchSize` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Networks::NetworkShardThreshold` (r:0 w:1)
	/// Proof: `Networks::NetworkShardThreshold` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Networks::NetworkShardTaskLimit` (r:0 w:1)
	/// Proof: `Networks::NetworkShardTaskLimit` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Networks::NetworkUnregOpExecGas` (r:0 w:1)
	/// Proof: `Networks::NetworkUnregOpExecGas` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Networks::NetworkBatchExecGas` (r:0 w:1)
	/// Proof: `Networks::NetworkBatchExecGas` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Networks::NetworkMsgByteGas` (r:0 w:1)
	/// Proof: `Networks::NetworkMsgByteGas` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Networks::NetworkBatchGasLimit` (r:0 w:1)
	/// Proof: `Networks::NetworkBatchGasLimit` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn set_network_config() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `454`
		//  Estimated: `3919`
		// Minimum execution time: 49_071_000 picoseconds.
		Weight::from_parts(50_204_000, 0)
			.saturating_add(Weight::from_parts(0, 3919))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(11))
	}
	/// Storage: `Networks::NetworkShardSize` (r:0 w:1)
	/// Proof: `Networks::NetworkShardSize` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Networks::NetworkMsgOpExecGas` (r:0 w:1)
	/// Proof: `Networks::NetworkMsgOpExecGas` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Networks::Networks` (r:0 w:1)
	/// Proof: `Networks::Networks` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Networks::NetworkRegOpExecGas` (r:0 w:1)
	/// Proof: `Networks::NetworkRegOpExecGas` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Networks::NetworkBatchSize` (r:0 w:1)
	/// Proof: `Networks::NetworkBatchSize` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Networks::NetworkName` (r:0 w:1)
	/// Proof: `Networks::NetworkName` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Networks::NetworkShardThreshold` (r:0 w:1)
	/// Proof: `Networks::NetworkShardThreshold` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Networks::NetworkShardTaskLimit` (r:0 w:1)
	/// Proof: `Networks::NetworkShardTaskLimit` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Networks::NetworkUnregOpExecGas` (r:0 w:1)
	/// Proof: `Networks::NetworkUnregOpExecGas` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Networks::NetworkBatchExecGas` (r:0 w:1)
	/// Proof: `Networks::NetworkBatchExecGas` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Networks::NetworkGatewayAddress` (r:0 w:1)
	/// Proof: `Networks::NetworkGatewayAddress` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Networks::NetworkGatewayBlock` (r:0 w:1)
	/// Proof: `Networks::NetworkGatewayBlock` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Networks::NetworkMsgByteGas` (r:0 w:1)
	/// Proof: `Networks::NetworkMsgByteGas` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Networks::NetworkBatchGasLimit` (r:0 w:1)
	/// Proof: `Networks::NetworkBatchGasLimit` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn remove_network() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 39_834_000 picoseconds.
		Weight::from_parts(43_440_000, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(14))
	}
}
