name: "Build GMP contracts"
description: "Action to build GMP smart contracts"

inputs:
  version:
    description: "Docker image version tag"
    required: true
    default: "dev"
  token:
    description: "Github API Token"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
    - name: Build contracts
      shell: bash
      run: forge build --root analog-gmp
