[package]
name = "e2e-tests"
authors.workspace = true
edition.workspace = true
version.workspace = true
homepage.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
futures.workspace = true
hex.workspace = true
serde_yaml = "0.9.34"
tc-cli= { path = "../tc-cli", features = ["testnet", "develop"] }
tempfile = "3.19.0"
testcontainers = "0.23.3"
time-primitives = { workspace = true, features = ["testnet", "develop"] }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
tracing.workspace = true
tracing-subscriber.workspace = true
