
//! Autogenerated weights for `pallet_tesseract_sig_storage`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-05-25, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `ip-172-31-17-194.us-east-2.compute.internal`, CPU: `Intel(R) Xeon(R) Platinum 8151 CPU @ 3.40GHz`
//! EXECUTION: None, WASM-EXECUTION: Compiled, CHAIN: None, DB CACHE: 1024

// Executed Command:
// ../target/release/timechain-node
// benchmark
// pallet
// --pallet
// pallet_tesseract_sig_storage
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// ../runtime/src/weights/sig_storage.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_tesseract_sig_storage`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_tesseract_sig_storage::WeightInfo for WeightInfo<T> {
	/// Storage: TesseractSigStorage SignatureStoreData (r:0 w:1)
	/// Proof Skipped: TesseractSigStorage SignatureStoreData (max_values: None, max_size: None, mode: Measured)
	/// The range of component `s` is `[0, 255]`.
	fn store_signature(_s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 13_280_000 picoseconds.
		Weight::from_parts(14_047_964, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: TesseractSigStorage TssGroupKey (r:0 w:1)
	/// Proof Skipped: TesseractSigStorage TssGroupKey (max_values: None, max_size: None, mode: Measured)
	/// The range of component `s` is `[1, 255]`.
	fn submit_tss_group_key(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 12_602_000 picoseconds.
		Weight::from_parts(13_191_080, 0)
			.saturating_add(Weight::from_parts(0, 0))
			// Standard Error: 95
			.saturating_add(Weight::from_parts(1_199, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: TesseractSigStorage TssShards (r:1 w:1)
	/// Proof Skipped: TesseractSigStorage TssShards (max_values: None, max_size: None, mode: Measured)
	/// The range of component `s` is `[1, 256]`.
	fn register_shard(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `3471`
		// Minimum execution time: 16_704_000 picoseconds.
		Weight::from_parts(17_499_315, 0)
			.saturating_add(Weight::from_parts(0, 3471))
			// Standard Error: 111
			.saturating_add(Weight::from_parts(734, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
