config:
  chronicle_funds: 1.
  timechain_url: 'wss://rpc.development.analog.one'
  prices_path: 'prices.csv'
  testers_path: 'testers.csv'
backends:
  evm:
    proxy: "evm/ERC1967Proxy.sol/ERC1967Proxy.json"
    gateway: "evm/Gateway.sol/Gateway.json"
    tester: "evm/GmpProxy.sol/GmpProxy.json"
networks:
  0:
    backend: "grpc"
    name: "grpc-1"
    url: "https://gmp-grpc-1.development.analog.one:443"
    coin_id: "usd-coin"
    currency_decimals: 6
    currency_symbol: USDT
    admin_funds: 100.
    gateway_funds: 10.
    chronicle_funds: 10.
    shard_size: 1
    shard_threshold: 1
    shard_task_limit: 50
    batch_size: 64
    batch_offset: 0
    batch_gas_limit: 10000000
    route_max_gas_limit: 1000000
    route_msg_fee: 0
    batch_exec_gas: 68193
    reg_op_exec_gas: 99121
    unreg_op_exec_gas: 26528
    msg_op_exec_gas: 33761
    msg_byte_gas: 20
    msg_session_gas: 53001
    max_gas_price: 1

  1:
    backend: "grpc"
    name: "grpc-2"
    url: "https://gmp-grpc-2.development.analog.one:443"
    coin_id: "usd-coin"
    currency_decimals: 6
    currency_symbol: USDT
    admin_funds: 100.
    gateway_funds: 10.
    chronicle_funds: 10.
    shard_size: 1
    shard_threshold: 1
    shard_task_limit: 50
    batch_size: 64
    batch_offset: 0
    batch_gas_limit: 10000000
    route_max_gas_limit: 1000000
    route_msg_fee: 0
    batch_exec_gas: 68193
    reg_op_exec_gas: 99121
    unreg_op_exec_gas: 26528
    msg_op_exec_gas: 33761
    msg_byte_gas: 20
    msg_session_gas: 53001
    max_gas_price: 1

chronicles:
- https://chronicle-1.development.analog.one
- https://chronicle-2.development.analog.one
- https://chronicle-3.development.analog.one
- https://chronicle-4.development.analog.one
- https://chronicle-5.development.analog.one
- https://chronicle-6.development.analog.one
- https://chronicle-7.development.analog.one
- https://chronicle-8.development.analog.one
- https://chronicle-9.development.analog.one
- https://chronicle-10.development.analog.one
- https://chronicle-11.development.analog.one
- https://chronicle-12.development.analog.one
