[package]
name = "tc-subxt-metadata"
version = "0.3.0"

authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
subxt.workspace = true

time-primitives = { workspace = true, default-features = true }

# Not used directly, but build runtime and to generate metadata
timechain-runtime.workspace = true

[features]
testnet = [
  "time-primitives/testnet",
  "timechain-runtime/testnet",
]
develop = [
  "time-primitives/develop",
  "timechain-runtime/develop",
]
