name: Build Docker tc-cli
on:
  push:
    paths-ignore:
      - '.github/**'
      - '!.github/workflows/merge-docker-tc-cli.yaml'
      - '.cargo/**'
      - 'chronicle/**'
      - 'docs/**'
      - 'e2e-tests/**'
      - 'node/**'
      - 'tss/**'
      - 'slack-bot/**'
      - 'utils/**'
    branches:
      - 'development'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  DOCKER_REPO: analoglabs/tc-cli
jobs:
  set-tags:
    name: Get & set tags
    runs-on: ubuntu-latest
    outputs:
      commit_hash: ${{ steps.get-sha.outputs.sha }}
      commit_hash8: ${{ steps.get-sha.outputs.sha8 }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get SHA
        id: get-sha
        run: |
          sha=$(git log -1 --format='%H')
          echo "sha=$sha" >> $GITHUB_OUTPUT
          echo "sha8=$(git log -1 --format='%H' | cut -c1-8)" >> $GITHUB_OUTPUT
          echo "SHA commit:" $sha
  build-binary:
    name: Build Docker image
    needs: ["set-tags"]
    runs-on: ["self-hosted", "container"]
    steps:
      - name: Fetch latest code
        uses: actions/checkout@v3
      - name: Setup foundry and build GMP contracts
        uses: ./.github/actions/build-contracts-tc-cli
      - name: Build and push
        uses: ./.github/actions/buildah-action
        with:
          image_name: ${{ env.DOCKER_REPO }}
          containerfile: ./config/docker/Dockerfile.tc-cli-release
          context: docker
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          registry: docker.io
          push: 'true'
          tags: ${{ needs.set-tags.outputs.commit_hash8 }},latest
