# Triggered via !ci-benchmark tag
name: Update runtime weights
on:
  pull_request:
    types: [labeled, unlabeled, opened, reopened, synchronize]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-benchmark:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.pull_request.labels.*.name,'!ci-benchmark-custom') || contains(github.event.pull_request.labels.*.name,'!ci-benchmark-frame') }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: mainnet
            profile: mainnet
            features: default
          - name: staging
            profile: testnet
            features: develop
          - name: testnet
            profile: testnet
            features: testnet
          - name: develop
            profile: testnet
            features: testnet,develop
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install dependencies
        run: sudo apt-get install -y protobuf-compiler
      - name: Build runtime benchmarks
        uses: ./.github/actions/cargo-command
        with:
          package: timechain-node
          profile: ${{ matrix.profile }}
          feature: runtime-benchmarks,${{ matrix.features }}
      - name: Upload runtime benchmarks
        uses: actions/upload-artifact@v4
        with:
          name: runtime-benchmarks-${{ matrix.name }}
          if-no-files-found: error
          path: target/${{ matrix.profile }}/timechain-node
  run-benchmark-custom-mainnet:
    needs: [build-benchmark]
    runs-on: [self-hosted, benchmark]
    if: ${{ contains(github.event.pull_request.labels.*.name,'!ci-benchmark-custom') }}
    strategy:
      fail-fast: false
      matrix:
        target: [mainnet, staging]
        pallet: [launch]
    steps:
      - name: Download runtime benchmarks
        uses: actions/download-artifact@v4
        with:
          name: runtime-benchmarks-${{ matrix.target }}
      - name: Prepare runtime benchmarks
        run: chmod +x timechain-node && mkdir -p ${{ matrix.target }}
      - name: Run runtime benchmarks
        run: ./timechain-node benchmark pallet --chain dev --pallet pallet_${{ matrix.pallet }} --extrinsic '*' --output ./${{ matrix.target }}/pallet_${{ matrix.pallet }}.rs
      - name: Upload weights
        uses: actions/upload-artifact@v4
        with:
          name: weights-${{ matrix.target }}-${{ matrix.pallet }}
          if-no-files-found: error
          path: ${{ matrix.target }}/${{ matrix.pallet }}.rs
  run-benchmark-custom-testnet:
    needs: [build-benchmark]
    runs-on: [self-hosted, benchmark]
    if: ${{ contains(github.event.pull_request.labels.*.name,'!ci-benchmark-custom') }}
    strategy:
      fail-fast: false
      matrix:
        target: [testnet, develop]
        pallet: [elections, members, networks, shards, tasks, timegraph, dmail]
    steps:
      - name: Download runtime benchmarks
        uses: actions/download-artifact@v4
        with:
          name: runtime-benchmarks-${{ matrix.target }}
      - name: Prepare runtime benchmarks
        run: chmod +x timechain-node && mkdir -p ${{ matrix.target }}
      - name: Run runtime benchmarks
        run: ./timechain-node benchmark pallet --chain dev --pallet pallet_${{ matrix.pallet }} --extrinsic '*' --output ./${{ matrix.target }}/pallet_${{ matrix.pallet }}.rs
      - name: Upload weights
        uses: actions/upload-artifact@v4
        with:
          name: weights-${{ matrix.target }}-${{ matrix.pallet }}
          if-no-files-found: error
          path: ${{ matrix.target }}/${{ matrix.pallet }}.rs
  run-benchmark-frame-baremetal:
    needs: [build-benchmark]
    runs-on: [self-hosted, baremetal-bench]
    if: ${{ contains(github.event.pull_request.labels.*.name,'!ci-benchmark-frame') }}
    strategy:
      fail-fast: false
      matrix:
        target: [mainnet, testnet]
        pallet: [frame_system, pallet_balances, pallet_timestamp, pallet_im_online, pallet_utility, pallet_bags_list, pallet_proxy, pallet_multisig]
    steps:
      - name: Download runtime benchmarks
        uses: actions/download-artifact@v4
        with:
          name: runtime-benchmarks-${{ matrix.target }}
      - name: Prepare runtime benchmarks
        run: chmod +x timechain-node && mkdir -p ${{ matrix.target }}
      - name: Run runtime benchmarks for pallets
        run: ./timechain-node benchmark pallet --chain dev --pallet ${{ matrix.pallet }} --extrinsic '*' --output ./${{ matrix.target }}/${{ matrix.pallet }}.rs
      - name: Upload weights
        uses: actions/upload-artifact@v4
        with:
          name: weights-${{ matrix.target }}-${{ matrix.pallet }}
          if-no-files-found: error
          path: ${{ matrix.target }}/${{ matrix.pallet }}.rs
  run-benchmark-frame-cloud:
    needs: [build-benchmark]
    runs-on: [self-hosted, benchmark]
    if: ${{ contains(github.event.pull_request.labels.*.name,'!ci-benchmark-frame') }}
    strategy:
      fail-fast: false
      matrix:
        target: [staging, develop]
        pallet: [frame_system, pallet_balances, pallet_timestamp, pallet_im_online, pallet_utility, pallet_bags_list, pallet_proxy, pallet_multisig]
    steps:
      - name: Download runtime benchmarks
        uses: actions/download-artifact@v4
        with:
          name: runtime-benchmarks-${{ matrix.target }}
      - name: Prepare runtime benchmarks
        run: chmod +x timechain-node && mkdir -p ${{ matrix.target }}
      - name: Run runtime benchmarks for pallets
        run: ./timechain-node benchmark pallet --chain dev --pallet ${{ matrix.pallet }} --extrinsic '*' --output ./${{ matrix.target }}/${{ matrix.pallet }}.rs
      - name: Upload weights
        uses: actions/upload-artifact@v4
        with:
          name: weights-${{ matrix.target }}-${{ matrix.pallet }}
          if-no-files-found: error
          path: ${{ matrix.target }}/${{ matrix.pallet }}.rs
  update-weights-frame:
    needs: [run-benchmark-custom-mainnet, run-benchmark-custom-testnet, run-benchmark-frame-cloud, run-benchmark-frame-baremetal]
    runs-on: [self-hosted, benchmark]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          submodules: recursive
      - name: Download mainnet weights
        uses: actions/download-artifact@v4
        with:
          path: runtime/src/weights/mainnet
          pattern: weights-mainnet-*
          merge-multiple: true
      - name: Download staging weights
        uses: actions/download-artifact@v4
        with:
          path: runtime/src/weights/staging
          pattern: weights-staging-*
          merge-multiple: true
      - name: Download testnet weights
        uses: actions/download-artifact@v4
        with:
          path: runtime/src/weights/testnet
          pattern: weights-testnet-*
          merge-multiple: true
      - name: Download develop weights
        uses: actions/download-artifact@v4
        with:
          path: runtime/src/weights/develop
          pattern: weights-develop-*
          merge-multiple: true
      - name: Commit updated weights
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.email "github@analog.one"
          git config user.name "Weights Update Bot"
          git commit -am "runtimes: automatic weights update"
          git push
