name: Run end-to-end tests
on:
  pull_request:
    types: [labeled, unlabeled, opened, reopened, synchronize]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  e2e-tests:
    runs-on: [self-hosted, integration]
    timeout-minutes: 90
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Rust cache
        uses: actions/cache@v4
        continue-on-error: false
        with:
          path: |
            ~/.cargo/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Build dev containers
        run: |
          ./scripts/build_docker.sh

      - name: Build testsuite
        uses: ./.github/actions/cargo-command
        with:
          command: test
          package: e2e-tests
          args: --no-run
          # Handling cache in the Actions Cache
          cache: false

      - name: Run testsuite
        uses: ./.github/actions/cargo-command
        with:
          command: test
          package: e2e-tests
          cache: false
          annotate: false

      - name: Cleanup
        if: always()
        run: |
          rm -rf /tmp/*.tar.zst
          sudo rm -rf /tmp/.tmp*
          docker ps -q --filter name=tmp | xargs docker stop || true
          docker container ls -a -q --filter name=tmp | xargs docker rm || true
          docker network ls -q --filter name=tmp | xargs docker network rm || true
