name: test

on:
  pull_request:
    paths:
      - 'gmp/evm/gateway/**'

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install Soldeer dependencies
        run: cd gmp/evm/gateway && forge soldeer install

      - name: Run Forge build
        run: |
          cd gmp/evm/gateway && forge --version
          cd gmp/evm/gateway && forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          cd gmp/evm/gateway && forge test -vvv
        id: test

      - name: Run Forge fmt
        run: |
          cd gmp/evm/gateway && forge fmt --check
        id: fmt
